version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /Logo\.png
  static_files: Logo.png
  upload: Logo\.png

- url: /assets
  static_dir: assets

- url: /.*
  static_files: index.html
  upload: index\.html
